version: "3.9"

services:
  db:
    image: postgres:14.6
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - .:/static:/static
    depends_on:
      - db

volumes:
  pg-data:
  static: