# Generated by Django 4.1.3 on 2023-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFinderCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('class_job_level_required', models.IntegerField()),
                ('item_level_required', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField(null=True)),
                ('accept_class_job_category', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Content Finder Condition',
            },
        ),
    ]
