# Generated by Django 4.1.3 on 2023-03-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='lodestone_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
