# Generated by Django 4.1.3 on 2023-03-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'verbose_name': 'Bookmarks'},
        ),
    ]
