# Generated by Django 4.1.3 on 2023-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_firebaseuser_lodestone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFinderCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('class_job_level_required', models.IntegerField()),
                ('item_level_required', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('accept_class_job_category', models.JSONField()),
            ],
        ),
    ]
