# Generated by Django 4.1.3 on 2023-03-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bookmarks_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Bookmark'},
        ),
        migrations.AlterField(
            model_name='firebaseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
