# Generated by Django 4.1.3 on 2023-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contentfindercondition_content_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfindercondition',
            name='accept_class_job_category',
            field=models.JSONField(null=True),
        ),
    ]
