# Generated by Django 4.1.3 on 2023-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_bookmarks_bookmark_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
