# Generated by Django 4.1.3 on 2023-05-11 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contentfindercondition_accept_class_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_id', models.IntegerField(null=True)),
                ('value', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Instance Content Bookmark',
            },
        ),
        migrations.AlterModelOptions(
            name='contentfindercondition',
            options={'verbose_name': 'Content Finder Condition'},
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.AddField(
            model_name='instancecontentbookmark',
            name='content_finder_condition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentfindercondition'),
        ),
        migrations.AddField(
            model_name='instancecontentbookmark',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
