# Generated by Django 4.1.3 on 2023-05-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_instancecontentbookmark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancecontentbookmark',
            old_name='user_id',
            new_name='user',
        ),
    ]
