# Generated by Django 4.1.3 on 2023-05-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_id_instancecontentbookmark_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancecontentbookmark',
            old_name='content_finder_condition_id',
            new_name='content_finder_condition',
        ),
    ]
