# Generated by Django 4.1.3 on 2022-11-21 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind_kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancecontent',
            name='required_level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
