# Generated by Django 4.1.3 on 2022-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind_kit', '0003_instancecontent_clear_exp_instancecontent_clear_gil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancecontent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
