# Generated by Django 4.1.3 on 2022-11-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind_kit', '0005_alter_instancecontent_required_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancecontent',
            name='clear_exp',
        ),
        migrations.RemoveField(
            model_name='instancecontent',
            name='clear_gil',
        ),
        migrations.RemoveField(
            model_name='instancecontent',
            name='required_level',
        ),
        migrations.AlterField(
            model_name='instancecontent',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
