# Generated by Django 4.1.3 on 2022-11-21 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind_kit', '0006_remove_instancecontent_clear_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecontent',
            name='clear_exp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instancecontent',
            name='clear_gil',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instancecontent',
            name='required_level',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
