# Generated by Django 4.1.3 on 2022-11-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grind_kit', '0010_account_rename_userjob_job_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='job_id',
            new_name='jobs_id',
        ),
    ]
