# Generated by Django 4.1.3 on 2022-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind_kit', '0013_alter_instancecontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancecontent',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
