# Generated by Django 4.1.3 on 2023-03-08 06:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customusermodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='userId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
